
name: CI/CD Workflow For appointment service

on:
  push:
    paths:
      - hospital-management/appointment-service

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Navigate to subfolder and run commands
      working-directory: 'hospital-management/appointment-service'
      run: |
        echo "Current directory: $(pwd)"
        ls

    - name: Perform Google Formatter check
      if: false
      working-directory: 'hospital-management/appointment-service'
      run: mvn com.spotify.fmt:fmt-maven-plugin:check

    - name: GitLeaks Scan
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: --path=hospital-management/appointment-service

    - name: OSS Scan
      working-directory: 'hospital-management/appointment-service'
      run: mvn ossindex:audit
      continue-on-error: true

    - name: OWASP Scan
      if: false
      working-directory: 'hospital-management/appointment-service'
      run: mvn org.owasp:dependency-check-maven:check

    - name: Build code and create Docker images
      working-directory: 'hospital-management/appointment-service'
      run: mvn clean install docker:build -Dimage.registry=${{vars.DOCKER_REGISTRY_USER}} -Dimage.tag=latest

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{vars.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PAT}}

    - name: Push Docker images
      run: |
        CURRENT_FOLDER_NAME=appointment-service
        docker push ${{vars.DOCKER_REGISTRY_USER}}/$CURRENT_FOLDER_NAME:latest
