name: Base Image Building Workflow for hospital management system

on:
  push:
    paths:
      - dev-sec-ops/base-images/license-finder


jobs:
  build-base-image-license-finder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Image license-finder
      run: docker build -t ${{vars.DOCKER_REGISTRY_USER}}/license-finder:latest -f dev-sec-ops/base-images/license-finder .

    - name: Login to Github Docker registery
      uses: docker/login-action@v2
      with:
        username: ${{vars.DOCKER_REGISTRY_USER}} 
        password: ${{secrets.DOCKER_REGISTRY_PAT}}

    - name: Push Docker Image
      run: docker push ${{vars.DOCKER_REGISTRY_USER}}/license-finder:latest 