name: CI/CD Workflow For directory service

on:
  push:
    branches:
      - main
    paths:
      - hospital-management/directory-service/**
      - .github/workflows/directory-service.yaml


jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Navigate to subfolder and run commands
      working-directory: 'hospital-management/directory-service'
      run: |
        echo "Current directory: $(pwd)"
        ls

    - name: Perform Google Formatter check
      working-directory: 'hospital-management/directory-service'
      run: mvn com.spotify.fmt:fmt-maven-plugin:check

    - name: GitLeaks Scan
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: --path=hospital-management/directory-service

    - name: OSS Scan
      working-directory: 'hospital-management/directory-service'
      run: mvn ossindex:audit
      continue-on-error: true

    - name: OWASP Scan
      if: false
      working-directory: 'hospital-management/directory-service'
      run: mvn org.owasp:dependency-check-maven:check

    - name: Build code and create Docker images
      working-directory: 'hospital-management/directory-service'
      run: mvn clean install docker:build -Dimage.registry=${{vars.DOCKER_REGISTRY_USER}} -Dimage.tag=$GITHUB_REF_NAME

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{vars.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PAT}}

    - name: Push Docker images
      run: |
        CURRENT_FOLDER_NAME=directory-service
        docker push ${{vars.DOCKER_REGISTRY_USER}}/$CURRENT_FOLDER_NAME:$GITHUB_REF_NAME
